SELECT USER_ID AS SELLER_ID, CASE WHEN U.FAVORITE_BRAND = A.ITEM_BRAND THEN 'yes' ELSE 'no' END AS 2ND_ITEM_FAV_BRAND
FROM USERS AS U
         LEFT JOIN (SELECT SELLER_ID, ITEM_BRAND, RANK() OVER (PARTITION BY SELLER_ID ORDER BY ORDER_DATE) AS `RANK`
                    FROM ORDERS AS O
                             INNER JOIN ITEMS AS I ON O.ITEM_ID = I.ITEM_ID) AS A
                   ON U.USER_ID = A.SELLER_ID AND `RANK` = 2
ORDER BY 1;