SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE
FROM (SELECT *,
             RANK() OVER (PARTITION BY USERNAME ORDER BY STARTDATE DESC) AS `RANK`,
             COUNT(*) OVER (PARTITION BY USERNAME)                       AS COUNT
      FROM USERACTIVITY) AS A
WHERE `RANK` = 2
   OR COUNT = 1;